//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webMensaje
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlMensaje
    {
        public long IDmensaje { get; set; }
        public System.DateTime fecha { get; set; }
        public string mensajeOriginal { get; set; }
        public string mensajeEncriptado { get; set; }
        public string mensajeRecibido { get; set; }
        public string mensajeCorregido { get; set; }
    }
}
